AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pull data from Earthquake,Universities REST API and loads into AWS RDS via S3.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  APIToS3ToDatabaseFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: API-S3-Database
      Description: Pull data from Earthquake,Universities REST API and loads into AWS RDS via S3.
      CodeUri: Src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Role: arn:aws:iam::230159725500:role/lambdas3fullaccess 
      Tracing: Active
      MemorySize: 10240
      Timeout: 900 
      Layers:
        - "arn:aws:lambda:us-east-2:230159725500:layer:requests:2"
        - "arn:aws:lambda:us-east-2:230159725500:layer:pandas-numpy-pytz-39:1"
        - "arn:aws:lambda:us-east-2:230159725500:layer:S3Fs39:13"
        -  "arn:aws:lambda:us-east-2:230159725500:layer:mysql:1"
      Environment:
        Variables:
          log_level : "ERROR"

Outputs:
  APIToS3ToDatabaseFunction:
    Description: "Pull data from Earthquake,Universities REST API and loads into AWS RDS via S3"
    Value: !GetAtt APIToS3ToDatabaseFunction.Arn